name: 构建 ImmortalWrt 24.10 x86 64

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Action
        uses: actions/checkout@v4.2.2

      - name: Docker Build ImmortalWrt
        run: |
          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
            -v "${{ github.workspace }}/x86-64/build.sh:/home/build/immortalwrt/build.sh" \
            immortalwrt/imagebuilder:x86-64-openwrt-24.10 \
            /bin/bash /home/build/immortalwrt/build.sh

      - name: Upload Releases
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: Autobuild-x86-64
          body_path: ${{ github.workspace }}/info.md
          files: |
            ${{ github.workspace }}/bin/targets/x86/64/immortalwrt*
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
