name: build-x86-64-immortalwrt-24.10

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build ImmortalWrt
        run: |
          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
            -v "${{ github.workspace }}/x86-64/24.10/build.sh:/home/build/immortalwrt/build.sh" \
            immortalwrt/imagebuilder:x86-64-openwrt-24.10 \
            /bin/bash /home/build/immortalwrt/build.sh

      - name: Generate Firmware SHA-256
        run: |
          for file in ${{ github.workspace }}/bin/targets/x86/64/*; do
            sha256sum "$file" > "${{ github.workspace }}/bin/targets/x86/64/$file.sha256"
            sha256sum -c "${{ github.workspace }}/bin/targets/x86/64/$file.sha256"
          done

      - name: Upload ImmortWrt as release assets
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: Autobuild-x86-64
          body_path: ${{ github.workspace }}/info.md
          files: |
            ${{ github.workspace }}/bin/targets/x86/64/*
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
